name: Build and Push Container Images

on:
  release:
    types: [published]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ./windows
          push: true
          tags: calebjstewart/pwncat-testing:windows

  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push CentOS Image
        uses: docker/build-push-action@v2
        with:
          context: ./centos
          push: true
          tags: calebjstewart/pwncat-testing:centos
      - name: Build and Push Ubuntu Image
        uses: docker/build-push-action@v2
        with:
          context: ./ubuntu
          push: true
          tags: calebjstewart/pwncat-testing:ubuntu
